### ISSUE TITLE
npm run dev 出错。

### ISSUE THREAD

**Issue by YaoaY** [MMF-FE/vue-typescript#4]
> ENV=dev node build/dev-server.js

'ENV' 不是内部或外部命令，也不是可运行的程序或批处理文件。

using npm@5.3.0
using node@v7.8.0

**Comment by YaoaY** [comment]
npm install cross-env --save-dev

`"dev": "cross-env ENV=dev node build/dev-server.js"`

这样可以解决。

**Comment by Allenice** [comment]
@YaoaY Fixed!
