### ISSUE TITLE
index.html 被生成到了奇怪的位置。

### ISSUE THREAD

**Issue by YaoaY** [MMF-FE/vue-typescript#5]
build 之后，index.html 被复制到了项目根目录里。
放在 dist/${env}/index.html 是不是更合适一点？

`index: path.resolve(__dirname, `../../index.html`)`
=>
`index: path.resolve(__dirname, `../../dist/${env}/index.html`)`

**Comment by Allenice** [comment]
@YaoaY 一般 html 页面都不生成在 dist 目录那里，dist 目录的东西同步到 CDN 上的，将 html 生成在那里没有意义。而且一般网站根目录都是直接设置成仓库根目录的。
